.travis.yml
https://datastax-oss.atlassian.net/browse/SPARKC-17
=> Added a few more tasks to travis ci

project/CassandraSparkBuild.scala, project/Settings.scala
=> #SPARKC-11 attempting to fix java assembly/publish

CHANGES.txt, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ReflectionUtil.scala, spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/util/ReflectionUtilSpec.scala
Seems there were some license changes in b1.1 which haven't been forward-merged to b1.2 and master.
=> Sparkc 107 b1.2

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/BoundStatementBuilder.scala
Adds Error for Join/Where Columns the Same
=> SPARKC-128: Parameterized Where in JWCassTable

doc/0_quick_start.md, doc/10_embedded.md, doc/11_metrics.md, doc/12_building_and_artifacts.md, doc/2_loading.md, doc/3_selection.md, doc/4_mapper.md, doc/5_saving.md, doc/8_streaming.md, doc/9_demos.md
I'll squash these before commit
=> SPARKC-122: Review/edit pass through all doc files

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionedRDD.scala
Reverts datastax/spark-cassandra-connector#635
=> Revert "SPARKC-126: Populate HostName & Address in preferredIps"

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
A full list of hosts should be saved in _config when opening
a new session, for the future use, in case some of the initial
hosts go down.
=> SPARKC-155: Update set of hosts in _config in openSession

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/ReplicaPartitioner.scala
Previously the code used CassandraConnector().hosts which only
used those hosts passed in the SparkConf object. Now host
retrevial is done via the Java Driver cluster metadata
object.
=> SPARKC-155: Get RPartitioner Hosts from Driver

CHANGES.txt, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/AbstractGettableData.scala
Quoted column name so that UDT type can find
the column
=> SPARKC-201 Support upper case charactors in UDT

README.md, doc/12_building_and_artifacts.md
- update caveat about Java API and Scala 2.11
- some general updates to Readme now that GitHub issues has been disabled for a while
=> Doc updates

doc/14_data_frames.md
I tried to create examples from the comments [here](https://github.com/datastax/spark-cassandra-connector/blob/master/spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/PredicatePushDown.scala#L8-L20):
```scala
/**
*  1. Only push down no-partition key column predicates with =, >, <, >=, <= predicate
*  2. Only push down primary key column predicates with = or IN predicate.
*  3. If there are regular columns in the pushdown predicates, they should have
*     at least one EQ expression on an indexed column and no IN predicates.
*  4. All partition column predicates must be included in the predicates to be pushed down,
*     only the last part of the partition key can be an IN predicate. For each partition column,
*     only one predicate is allowed.
*  5. For cluster …
```
=> added pushdown filter examples to documentation

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala, spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala
Added a recursive method to update Sql row column with timestamp
data
=> SPARKC-254 Added support timestamp in collection, udt and tuples

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala
When we read a UDT from a C* table it becomes nested generic
rows inside of dataframes. These nested row objects are not convertable
back into UDT types so they cannot be written back into C*. This patch
enables the conversion of nested GenericRows back into UDTS if the
naming is correct.
=> SPARKC-271: Let UDTs be converted from GenericRows

project/Settings.scala, project/SparkInstaller.scala, project/Versions.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraPrunedFilteredScanSpec.scala
Also change the connector version to 1.6.0-M1 and ignore broken tests (to be addressed in other tickets)
=> SPARKC-297: Set Spark version to 1.6.0-rc1

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/TupleValue.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/UDTValue.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/DefaultColumnMapper.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/ReflectionColumnMapper.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/TupleColumnMapper.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/AnyObjectFactory.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/ClassBasedRowReader.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverter.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/CollectionColumnType.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/ColumnType.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/PrimitiveColumnType.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TupleType.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/JavaApiHelper.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ReflectionUtil.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala, spark-cassandra-connector/src/main/scala/org/apache/spark/sql/catalyst/ReflectionLock.scala
Original patch by Fernando Jimenez <fernando.jimenez@wealthport.com>,
extended and ported to 1.4.
=> SPARKC-333: Fix reflection issue in scala 2.10

doc/9_demos.md
Correct demos urls in documentation
=> Correct demos urls in documentation

spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/DynamicCassandraPorts.scala
because the directory is resolve just once it's make an exception
=> Don't double resolve the file.

CHANGES.txt, doc/5_saving.md, doc/reference.md, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala, spark-cassandra-connector/src/main/java/com/datastax/spark/connector/japi/RDDAndDStreamCommonJavaFunctions.java, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WriteConf.scala
Added support for IF NOT EXISTS behaviour when inserting data and specifying ifNotExists = true in WriteConf.
=> SPARKC-362: Added support for INSERT ... IF NOT EXISTS

project/CassandraSparkBuild.scala, project/plugins.sbt, spark-cassandra-connector-perf/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDDBenchmark.scala, spark-cassandra-connector-perf/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDDData.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala
This is a backport of https://github.com/datastax/spark-cassandra-connector/pull/969
=> SPARKC-233 use executeAsync when joining with C* table

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/streaming/RDDStreamingSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala
Also make tests fail on exceptions thrown in forEachRDD
=> SPARKC-388 fix DStream repartitionByCassandraReplica and it's test

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/streaming/RDDStreamingSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala
=> SPARKC-388 fix DStream repartitionByCassandraReplica

doc/0_quick_start.md, doc/10_embedded.md, doc/12_building_and_artifacts.md, doc/13_1_setup_spark_shell.md, doc/13_spark_shell.md, doc/14_data_frames.md, doc/15_python.md, doc/1_connecting.md, doc/2_loading.md, doc/3_selection.md, doc/4_mapper.md, doc/5_saving.md, doc/6_advanced_mapper.md, doc/7_java_api.md
Attempting to enforce consistent Example tags (Helps with Linking)
All links updated to "latest" instead of a specific version
Some Contradictions removed
References to java module removed
Quick Start Simplified
=> Bringing our documentation up to date

project/Settings.scala, project/SparkCassandraConnectorBuild.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TimestampFormatter.scala
=> SPARKC-414: Remove Dependency on CassandraUtil

project/SparkCassandraConnectorBuild.scala
Advice from some helpful folks on sbt/sbt gitter noted that we should be
setting packagedArtifact in pacakageBin to reassign the publish
artifacts.
=> Set PackagedArtifact instead of PackagedArtifacts

project/Versions.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
This tests an error in Spark which was present in 2.0.0 but should be
fixed in 2.0.1
https://issues.apache.org/jira/browse/SPARK-17673
=> SPARKC-429: Test Reused Exchange SPARK-17673

project/plugins.sbt
=> [MINOR] Remove plugin duplicate

project/SparkCassandraConnectorBuild.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/JavaBeanColumnMapper.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/ReflectionColumnMapper.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala, spark-cassandra-connector/src/test/java/com/datastax/spark/connector/mapper/JavaTestBean.java, spark-cassandra-connector/src/test/java/com/datastax/spark/connector/mapper/JavaTestUDTBean.java, spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/mapper/JavaBeanColumnMapperTest.scala
New to Scala. Feel free to comment liberally :)
=> [SPARKC-427] Allow Java Object Mapped Beans with Annotations to have the name mappings honored

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala
9e111e1 (Russell Spitzer, 3 hours ago)
SPARKC-363: Find Converters for Classes on Different Classloaders
The current code assumes that if you are converting a UDT in a collection
or some other nested structure that all subclasses can be loaded on the
same classloader than the SCC has been loaded on. For some runtime
enivronments (like DSE) this is not true and the SCC is on a different
classloader than the application code. This can lead to the lookup on the
contained class failing with a ClassNotFound Exception.
To avoid this situation we allow for the first class (which will be tuned
to the correct classloader in it's runtime mirror) to force all
sub-converters created to enable it's construction to be built with the
same Classloader.
This fixes situations like
case class Row(k: Int, v: …
=> SPARKC-363: Classloader issues with UDTs on different Classloaders than SCC

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/SessionProxy.scala
Previously Session proxy would only proxy the Session interface. Here we
look up all available interfaces and proxy all of them.
=> SPARKC-476: SessionProxy Should proxy all Runtime Interfaces

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/MultipleRetryPolicy.scala
Null means using the statement's original query CL. This is important
because with LWT the CL returned by C* will not match the original
serial CL if the query is in it's non-serial portion. This forces the
original CL to be used regardless of server actions.
=> SPARKC-494: MultipleRetryPolicy should retry with null

doc/16_partitioning.md
=> doc: markdown typo - best commit in history

doc/7_java_api.md, spark-cassandra-connector/src/main/java/com/datastax/spark/connector/japi/CassandraJavaUtil.java
* Update `CassandraJavaUtil.java#mapToRow(Class, Map<String, String>)` and `CassandraJavaUtil.java#mapToRow(Class, Pair[])` javadocs to get more clear view on usage.
* Detailed Java API user guide with code examples.
=> Update Java API Documentation.

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala
Write time error exception had wrong message for RowReader
=> Update the WriteTime error exception for reader

doc/reference.md
Removed an extra copy of splitCount that was added in 6c81a54d59154c7fd84ab749df688327dc6f759e
=> Fixed Doc Issue

doc/0_quick_start.md, doc/10_embedded.md, doc/12_building_and_artifacts.md, doc/13_1_setup_spark_shell.md, doc/13_spark_shell.md, doc/15_python.md, doc/7_java_api.md, doc/8_streaming.md
- https where available
- one reference to a file which had been renamed
- couple external doc references which have moved
=> Fix several doc links

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala
Avoid overhead of repeated `columnTypes(i).converterToCassandra` which lead to synchronized reflection costly methods.
Profiling a spark job wich prepare a sstable from dataframe with many udt into collections, with project https://github.com/jparkie/Spark2Cassandra , up to 90% of the time is spent into `converterToCassandra` for the udt columns conversion
I just expand the memoization of converters we already have in `DriverUDTValueConverter` to the case class UDTFieldDef converter generator in converterToCassandra
I wasn't able to register on the jira project (in order to create a issue to associate to the PR) 
> datastax-oss.atlassian.net has reached its license limit.
[![Build Status](https://travis-ci.org/glutamatt/spark-cassandra-connector.svg?branch=master)](https://travis-ci.org/gl …
=> SPARKC-536 UDT converters optimization

project/Versions.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/ThrottlingSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/AsyncExecutor.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/QueryExecutor.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala, spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/writer/AsyncExecutorTest.scala
Requires increasing the driver target, all other changes
merge cleanly.
=> SPARKC-542: SPARKC-503 Backport

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/AnyObjectFactory.scala
If multiple threads attempt to convert an object at the same time
there is a chance of racing on filling the temporary arguement buffer.
The buffer is used to add in extra arguments that may be required if the
class has certain external references. To fix this we remove the buffer
entirely and add in the extra args (if they exist) by adding them
to the passed args with sequence concatination.
=> SPARKC-550: Fix Thread Safety Issue in AnyObjectFactory

project/Versions.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala, spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/streaming/CheckpointStreamSpec.scala, spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala, spark-cassandra-connector/src/test/java/com/datastax/spark/connector/japi/SparkContextJavaFunctionsTest.java
This is a fix for https://datastax-oss.atlassian.net/browse/SPARKC-553.
=> Update Spark version to 2.4.0 and make sure it is supported

README.md, doc/0_quick_start.md, doc/12_building_and_artifacts.md, doc/13_spark_shell.md, doc/14_data_frames.md, doc/15_python.md, doc/16_partitioning.md, doc/1_connecting.md, doc/data_source_v1.md, doc/developers.md
=> SPARKC-593 3.0 doc fixes

connector/src/it/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinSpec.scala
Expression strict matching used in CDJExec and CDJStrategy failed when
one of the expressions contained a qualifier. This failed Direct Join
recognition.
Since we care only about expression names and types, this commit
introduces a loosened expression comparison.
=> SPARKC-613 fix direct join for spark sql

connector/src/it/scala/com/datastax/spark/connector/cluster/Fixtures.scala, connector/src/it/scala/com/datastax/spark/connector/rdd/ReplicaRepartitionedCassandraRDDSpec.scala, connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala, connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
=> SPARKC-642 repartitionByCassandraReplica relocates data to the local node only

README.md
Update supported spark version in readme docs
=> Update supported spark version in readme docs

README.md
Update supported spark version in read me docs
=> Update supported spark version in read me docs

README.md
Update supported Spark version
=> Update supported Spark version

README.md
N/A - Update to `README.md` only.
Fixes: [SPARKC-694](https://datastax-oss.atlassian.net/browse/SPARKC-694)
N/A - Update to `README.md` only.
=> SPARKC-694 Fixed broken CLA link

README.md
Just a trivial update to community server to ask questions and get answered.
Manually verified the invite link works.
=> Doc update for community
