README.md

Because this change includes references to Spark 1.2, we could include just prior to putting out our first 1.2 alpha release.
Fixes #390

Add table to show version compatibility for different connector versions

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraStrategies.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraTableScan.scala

Spark 1.1.1 introduced a new InSet expression which is generated by the optimizer for "IN" filters where the values are literals. This PR was originally made for Spark 1.1.1 but is valid for Spark 1.2 as well. I've tested this on both Spark 1.1.1 and Spark 1.2, using the most recent commits. I added a simple integration test to ensure the predicate is pushed down as part of the CassandraTableScan versus SparkSQL filter.

Added support for InSet predicate

---

CHANGES.txt
project/Settings.scala
project/Versions.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraCatalog.scala

- changed Spark dependency version
- updated CassandraCatalog
- unlocked CassandraSQL tests which where ignored before
- increased max perm size for test

SPARKC-30: Upgrade to Spark 1.2.1

---

doc/5_saving.md

Added the "spark.cassandra.output.consistency.level" setting to the documentation.
Fixes #307

Updated docs

---

CHANGES.txt
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/CassandraJavaUtil.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDD.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDD.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnRef.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnSelector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala

With this patch:
- Added one more trait (SelectableColumnRef) in ColumnRef hierarchy to reflect columns without names
- Added CountColumn case class
- Refactored CassandraRDD, CassandraJavaRDD and CassandraJavaPairRDD
- added test cases
- CHANGES.txt

SPARKC-52: Support for native Cassandra count

---

CHANGES.txt
doc/3_selection.md
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDD.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDD.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/CassandraStreamingRDD.scala

With this patch:
- added limit method to CassandraRDD, CassandraJavaRDD and CassandraJavaPairRDD
- updated CQL generation method in CassandraRDD so that it can use the limit clause
- added test case
- updated documentation and CHANGES.txt

SPARKC-31: Added support for passing the limit clause to CQL in order to fetch top n results

---

CHANGES.txt
doc/3_selection.md
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDD.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDD.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ClusteringOrder.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/CassandraStreamingRDD.scala

With this patch:
- added withAscOrder and withDescOrder methods to CassandraRDD, CassandraJavaRDD and CassandraJavaPairRDD
- updated CQL generation method in CassandraRDD so that it can use the order by clause
- added test cases
- updated documentation and CHANGES.txt

SPARKC-32: Added support for pushing down order by clause

---

CHANGES.txt
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/CassandraJavaUtilSpec.scala
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/rdd/CassandraJavaRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/ClassBasedRowReader.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ReflectionUtil.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/DefaultRowWriter.scala
spark-cassandra-connector/src/test/java/com/datastax/spark/connector/SampleJavaBeanSubClass.java
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/util/ReflectionUtilSpec.scala

With this patch:
- Added test cases for CassandraRDD, TableWriter, CassandraJavaRDD and CassandraJavaUtil
- Updted test cases in ReflectionUtilSpec
- Fixed ClassBasedRowReader, DefaultRowWriter and ReflectionUtils so that they use member methods rather than declared methods

SPARKC-70: Fixed reading and writing objects with inherited fields

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala

row count is reported as 0 currently. As the number of rows is logged at
info level, this can be misleading. This fix passes the CountingIterator
to the batch builder.

fix to report the correct row count

---

CHANGES.txt
README.md
doc/2_loading.md
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/rdd/CassandraJavaRDDSpec.scala
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/SparkContextJavaFunctions.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/GroupingBatchBuilderSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/AbstractGettableData.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnSelector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/SparkContextFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/package.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/EmptyCassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/package.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionedRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraRDDPartition.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraRDDPartitioner.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/ReplicaPartitioner.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/CassandraStreamingRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/CountingIterator.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/DefaultRowWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/ReplicaMapper.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/RowWriterFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/SqlRowWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraTableScan.scala

Added function keyByReplica
For keying RDD's based on their cassandra replica placement
Added function partitionByReplica
Which keys an RDD based on replica placement then creates
new partitions based on their replicas

SPARKC-25: Initial work to allow RDD's to be used as Keys for C*

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/EmptyCassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/CassandraStreamingRDD.scala

Limit line length to 105 columns. No logic changed.

SPARKC-99: Code formatting and cleanup.

---

CHANGES.txt
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraRDDPartitioner.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/Murmur3PartitionerTokenRangeSplitter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/RandomPartitionerTokenRangeSplitter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/ServerSideTokenRangeSplitter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/TokenRangeClusterer.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/dht/TokenRange.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/partitioner/Murmur3PartitionerTokenRangeSplitterTest.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/partitioner/RandomPartitionerTokenRangeSplitterTest.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/partitioner/TokenRangeClustererTest.scala

Remove describe_ring call and replace it with native Java Driver support for fetching token ranges with corresponding replica sets from the Cluster metadata. Removed CassandraNode class, because now an endpoint is represented by only one address, taken from the Java driver Host object.  This is the first step towards removing thrift dependency from the connector code.

SPARKC-93:  Remove use of Thrift describe_ring.

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionedRDD.scala

For the preferredLocations method of the repartitionByCassandraReplica
use the Broadcast and Local Endpoints if possible.
For all usages make sure that the both hostname and address are used.

SPARKC-126: Populate HostName & Address in preferredIps

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/RateLimiter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/writer/RateLimiterSpec.scala

Two possible overflows fixed here,
Elapsed time * rate can overflow when lastTime is 0 --> Fixed this by starting last time at time()
rate at it's default will overflow since it is Int.MaxValue * 1024 * 1024 --> Fixed this by changing default to 1000000mbps
Also I set elapsed time to always be positive or 0 incase of ntp sync disrupting the clock and sending
time backwards.

SPARKC-139: Fix overflow bugs in RateLimiter

---

doc/5_saving.md
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WriteConf.scala

Added a message in the docs about long running job stability

SPARKC-142: New Defaults Based on Perf Tests

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala

Back porting SPARKC-126 to b1.1 branch, to help with task locality

SPARKC-141: BP SPARKC-126 (Pref Hostname and Adr)

---

project/Versions.scala

JIRA: https://datastax-oss.atlassian.net/browse/SPARKC-148
I have tested the lastest commit in master(https://github.com/datastax/spark-cassandra-connector/commit/72cd1e31cee2a60c0a27b4e9a3feb2287ef8f069), it works fine with Spark 1.3.1.

SPARKC-148: Update to Spark 1.3.1 in Version.scala

---

CHANGES.txt
doc/6_advanced_mapper.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/CollectionColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/ColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/PrimitiveColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/CassandraRowWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/DefaultRowWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/RowWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/SqlRowWriter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/writer/DefaultRowWriterTest.scala

RowWriter is always created at the application driver site and
serialized to Spark executors. RowWriter also has full
type information about the columns it writes. Therefore
it is a good place to instantiate proper TypeConverters and
completely handle the process of converting the RDD item object of
some type T to values that can be passed to the Java Driver API for
saving as a Cassandra row. When TypeConverters are instantiated
together with RowWriter, custom TypeConverters registered in the
driver application can be found.
Unfortunately this approach requires changes to how
TypeConverters are obtained. Some type converters, like the converter
used for converting UDTValues to objects passable to the Java Driver
API, depend strongly on Java Driver objects like DataType or
ProtocolVersion. …

SPARKC-157: Move type conversions back to RowWriters.

---

CHANGES.txt
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraStrategies.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/PredicateOps.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/PredicatePushDown.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/PredicatePushDownSpec.scala

PredicatePushDown class was tied to Spark code by depending on Spark's
internal Expression class. This caused a problem when we wanted to
unit-test it separately or when we wanted to support other
representation of predicates like the new Filter class introduced by
Spark Data Sources API.
Therefore in this ticket, PredicatePushDown class has been moved out
from CassandraStrategies into its own file. Then all Spark-specific
code has been factored out to a separate PredicateOps typeclass.
PredicatePushDown has been generified to take predicate class type
parameter. This way, it can work with any type of predicate that is
in PredicateOps. PredicateOps is available for Expression and Filter.
It is very easy to add support for other types of predicates in the
future without changing …

SPARKC-166: Refactoring: Decouple PredicatePushDown from SparkSQL

---

spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/ConsolidateSettingsSpec.scala

Store keyspace level settings as cluster.keyspace/xx.xx.xx.xx
and cluseter level settings as cluster/xx.xx.xx.xx in
SQLConf
Retrieve settings in the order of
table level -> keyspace -> cluster -> default. Use the one
first available.

SPARKS-162 Add keyspce level/cluster level Conf settings

---

project/Settings.scala

- no publish.version.type property -> "-SNAPSHOT"
- publish.version.type=release -> ""
- publish.version.type=commit-release -> "-123456" (commit sha)

SPARKC-170: Allow to easily switch version suffix by specifying system property

---

spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/ConsolidateSettingsSpec.scala

Store keyspace level settings as cluster.keyspace/xx.xx.xx.xx
and cluseter level settings as cluster/xx.xx.xx.xx in
SQLConf
Retrieve settings in the order of
table level -> keyspace -> cluster -> default. Use the one
first available.

SPARKC-162 Add keyspce level/cluster level Conf settings

---

doc/13_1_setup_spark_shell.md
doc/13_spark_shell.md

Attempts to make the how-to guide on using the Spark-Cassandra Connector with the Spark Shell more accessible by:
- moving detail information out of the main path, 
- adding a small paragraph on why this is needed
- some style refactoring
@RussellSpitzer what do you think?  (btw, I didn't know if I needed to track this into JIRA, and there's an umbrella story for that as well. https://datastax-oss.atlassian.net/browse/SPARKC-41  Let me know if I need to take action there in case this proposal is deemed of some use)

Easier spark shell "how-to" guide

---

project/CassandraSparkBuild.scala

Since this is shaded in Spark 1.2+ we need to include it in the
Connector Jar to make sure that the Java Driver has Guava.

SPARKC-176: Add Guava back to Assembly Jar

---

CHANGES.txt
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/rdd/CassandraJavaRDDSpec.scala
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/CassandraJavaUtil.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDD.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDD.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterColumnNamesSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnSelector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/ColumnMap.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/package.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/ClassBasedRowReader.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/ValueRowReader.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/DefaultRowWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraTableScan.scala

Cleanly cherry-picked the commit which fixed SPARKC-8
- Created case classes for different kinds of columns
- Changed the way the columns can be selected - select method now accepts SelectionColumn instead of String arguments
- Updated JavaAPI for TTL and write time retrieval support
- Updated and added test cases for TTL and write time retrieval support
- Updated API docs
- Applied reviewer's comments - merged ColumnSelection hierarchy into ColumnRef
- Add extractor to NamedColumnRef and use it.

SPARKC-169: Backport of SPARKC-8: Reading TTL and write time of regular columns

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala

Previously keyspace/table not found messages were displayed as "key x
not found". With this patch we add in the same suggestion functionality
for the DataFrames API that exists with the normal RDD code. We attempt
to retreive keyspace and table metadata from C* and if it fails we
fall back on our suggestion utility.

SPARKC-186: Table and Keyspace Name suggestions in DataFrames API

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnSelector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/ColumnSelectorSpec.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/TableDefSpec.scala

This patch removes `select` method from `TableDef` because this method turned out to be redundant
and making a circular dependency to `ColumnSelector`. Instead of pattern matching in this method,
the proper column sequence is obtained directly in `ColumnSelector.selectFrom` method.
The exceptions have been aligned and the test cases have been moved to `ColumnSelectorSpec`.
The case when `TableDef.select` method gets `SomeColumns` where never used but in the tests.

SPARKC-177: Refactored ColumnSelector

---

doc/2_loading.md
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/rdd/CassandraJavaRDDSpec.scala
spark-cassandra-connector-java/src/main/scala/com/datastax/spark/connector/japi/JavaGettableByIndexData.scala
spark-cassandra-connector-java/src/main/scala/com/datastax/spark/connector/japi/JavaGettableData.scala
spark-cassandra-connector-java/src/main/scala/com/datastax/spark/connector/japi/TupleValue.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/GettableByIndexData.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/GettableData.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ScalaGettableByIndexData.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/TupleValue.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/UDTValue.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/ColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/Symbols.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverterTest.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeConverterTest.scala

This ticket introduces a new TupleValue class for storing Cassandra
tuples. Because tuples don't have named components, we moved all
the "by-index" getters out of GettableData to a new
GettableByIndex trait, implemented by TupleValue. TupleValue serves
the same purpose as Java Driver TupleValue class, but contrary to
that class, it is Serializable and hooks into the TypeConverter system
so it supports specific Scala types. An analogue TupleValue class
has been introduced in the Java API.
TupleValues can be nested in CassandraRows, UDTValues or other
TupleValues. In order to get TupleValues from  CassandraRows or
UDTValues, a new method getTupleValue has been added to the
ScalaGettableData,  ScalaGettableByIndexData, JavaGettableData and
JavaGettableByIndexData.
Direct mapping from …

SPARKC-172: Support for Cassandra tuples

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala

Spark 1.4.0 expects UTF8String instead of String.
It also does not expect Sets, so Sets are converted to Seqs.

SPARKC-195: Fix CassandraSQLRow component data types

---

doc/14_data_frames.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DefaultSource.scala

Renamed c_table to table.
Renamed push_down to pushdown.
The reason for this is that, probably due to a bug, Spark 1.4.0 does not accept underlines in data source options.

SPARKC-194: Remove underlines from Cassandra DataSource options.

---

CHANGES.txt
doc/5_saving.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/TupleColumnMapper.scala

Currently there is no way to specify only certain elements of a tuple
in a column mapper for savingToCassandra or for using
partitionByCassandraReplica. This patch allows usage of the "as" syntax
to also apply to tuple field names "_1" ,"_2" so if a tuple was provdied
like (int,int,int,int) one could specify "Pkey" as "_3", "ckey" as "_2"

SPARKC-125: Allow aliases to be used with tuples

---

CHANGES.txt
doc/5_saving.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnRef.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala

Previously all statements with collections were treated as overwrites
limiting user's abiilty to modify collections in batch. This patch
provides new options within the ColumnMapper api to allow
- Appending (Lists)
- Prepending (Lists)
- Adding (Sets, Maps, Lists)
- Removing (Lists, Sets)
Removal of elements from maps is currenlty not supported as it would
require much more complicated syntax wrangiling and will be left for a
later ticket if anyone desires the functionality.
To accomplish this a new ColumnRef was created CollectionColumnRef
which contains one additional element CollectionBehavior. TableWriter
now directly takes the ColumnSelector so that it can access these
ColumnBehvaiors when crafting the CQL to do the update.

SPARKC-147: Modify C* collections from Spark

---

CHANGES.txt
doc/2_loading.md
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/RDDJavaFunctions.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/ReplicaMapper.scala

Previously we relied on the implicit mapping of rdd to CassandraRows to
determine a the Primary Key present in the RDD. This patch allows the
user to specify using a column mapper the mapping between the partition
key and the RDD. The interface is the same as if they were saving to
Cassandra.

SPARKC-104 Add partitionKeyMapper to repartitionByCassandraReplica()

---

spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/SparkTemplate.scala
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/CassandraJavaUtilSpec.scala
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/rdd/CassandraJavaPairRDDSpec.scala
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/rdd/CassandraJavaRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraAuthenticatedConnectorSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraPartitionKeyWhereSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/SchemaSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/repl/CassandraRDDReplSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLClusterLevelSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/util/MultiThreadedSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/GroupingBatchBuilderSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/RoutingKeyGeneratorSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterColumnNamesSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala

To test on external Cassandra nodes, export following
properties
export IT_TEST_CASSANDRA_HOSTS=192.168.123.10,127.0.0.1
export IT_TEST_CASSANDRA_RPC_PORTS=9160, 9161
export IT_TEST_CASSANDRA_NATIVE_PORTS=9042,9043

SPARKC-178 Fixed IT tests with external Cassandra nodes

---

CHANGES.txt
doc/7_java_api.md
spark-cassandra-connector-java/src/it/scala/com/datastax/spark/connector/CassandraJavaUtilSpec.scala
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/CassandraJavaUtil.java

Added methods to CassandraJavaUtil which allow to create RowReaderFactory and RowWriterFactory for tuples.

SPARKC-206: Tuples support in Java API

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala

Increase the number of iterations in the warm-up phase of the test.
Make the test condition less restrictive, but still enough
restrictive to catch leaks of 1 thread per RDD.

SPARKC-205: Improve thread leak test.

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala

The parameter spark.cassandra.input.split_size_in_mb now sets the
size in megabytes, not bytes.

SPARKC-208: Fix setting split size in MB

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala

Added Thread.sleep before measuring active thread count. It looks
like Spark 1.3 is not immediately terminating some worker threads after
doing all the work.

SPARKC-205: Improve thread-leak test even more

---

doc/14_data_frames.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala

This switches the tests from the .load(source,options) to the new
.read.format(source).options(options).load syntax which is now defined
in the SPARK 1.4 Dataframes API. A similar switch happened for the
saving operations.

SPARKC-210: Update DataFrame Tests and Docs to 1.4 API

---

CHANGES.txt
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraRelation.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DataTypeConverter.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/types/InetAddressType.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/types/UUIDType.scala

Add custom UUIDType and InetAddressType
UUIDType uses JVM data type UUID as base
InetAddressType uses JVM data type InetAddress as base
Since there is no way to convert a String to
UUID/InetAddress from a SQL query. The correct query
should be like
select * from table
where CAST(inet_address_column as string)
= '/74.125.239.135'
It errors out for the query
select * from table
where inet_address_column = '/74.125.239.135'
Because that Spark internally CAST string
'/74.125.239.135' to a Double.
Same should apply to UUID as well

SPARKC-129 Add custom UUIDType and InetAddressType

---

CHANGES.txt
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDD.java
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDD.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/EmptyCassandraRDD.scala

Previously native Cassandra count overrode `count` method from RDD. Because of
some request for more control when to execute native count and when not to, we
renamed Cassandra native count to `cassandraCount`. Now `count` is pure Spark
count.

SPARKC-215: Cassandra native count is performed by `cassandraCount` method

---

CHANGES.txt
doc/1_connecting.md
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/MultipleRetryPolicy.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/CassandraConnectorConfSpec.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/RetryDelayConfSpec.scala

A new configuration parameters has been introduced which can configure
various delays and delay calculation methods. It is possible to configure
a constant delay, linearly increasing delay and exponentially increasing
delay.

SPARKC-221: Added configurable delay between subsequent query retries

---

doc/5_saving.md
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WriteConf.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/writer/WriteConfTest.scala

We found that having only a whole number granularity made it difficult
to actually tune the output to get maximum throuhgput. This ticket
allows the conf to be set to a double rather than an Int providing the
end user with a much greater ability to control thorughput while
maintaining backwards compatibility.

SPARKC-226: Change output.TP_mb_per_sec -> double

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraSSLConnectorSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/RefCountedCache.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/CassandraConnectorConfSpec.scala

The bug here is that an Array(enabledAlgorithms) will not match another
Array even if their contents match exactly. This will happen even if the
array is declared statically and finally. To fix this we need to change
the enabledAlgorithms variable to a Set which is more appropriate for
this field as well (Since order and duplicates do not matter). The
original decision to make this an Array was most likely done to match
the Java Driver's implementation, unfortunately this has some bad
implications for the underlying connection pool which we can avoid with
a Set.
Since the Hash of the CassandraConnectionConf is used by
the Cache to determine whether or not a new Cluster object needs to be
made, using an Array forces the creation of a new Cluster object on
every write. These cannot be …

SPARKC-227: Fix Connection Caching, Change SSL EnabledAlgorithms to Set

---

doc/2_loading.md

Since 1.3.0 SchemaRDD in deprecated in favor of DataFrame

Minor doc improvement

---

CHANGES.txt
project/BuildUtil.scala
project/Settings.scala
project/SparkInstaller.scala
project/Versions.scala

Set the Spark version to <branch_name>-SNAPSHOT or to v<x.y.z> and the build
script will automatically fetch Spark from GIT at that version, build it and install
you the local Maven repository. Finally it will be used. Works also with IDEA.

SPARKC-242: Added ability to build against unreleased Spark versions

---

spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/SparkTemplate.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala

Three tests in particular in the IT suite were constantly logging ERRORs
as the executor processes terminated. These messages were expected since
these tests were meant to raise exceptions. To avoid having noisy logs a
withoutLogging wrapper was added which turns off logging for the
duration of a test case.

SPARKC-223: Add withoutLogging for noisy tests

---

.gitignore
project/CassandraSparkBuild.scala
project/Settings.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/EmbeddedCassandra.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/SparkTemplate.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/streaming/RDDStreamSpec.scala

There is a separate, independent project - cassandra-server which has a single
dependency - cassandra-all with transitive dependencies.
Classpath of this project is exported in env variable CASSANRA_CLASSPATH to JVM
running integration tests and used to run Cassandra.
Other changes:
- disable Spark UI for integration tests
- set SPARK_LOCAL_IP to 127.0.0.1 for integration tests

SPARKC-245: Separated Cassandra classpath from project classpath

---

doc/5_saving.md

I had to create a cassandra table with a more complicated primary key structure than shown in the documentation examples. I finally figured out how to do this from the source code and thought I could save some others time by sharing what I have done.

updated documentation to save others time doing what might be a common task

---

project/Versions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala

Updated to 3.0 version of the Java Driver. The getIndex call is no
longer valid for ColumnMetdata objects because in 3.0 columns can have
multiple indexes. To accomadate this we now use the list of all indexes
in the table to determine if any have targeted the column in question.

SPARKC-270: Updated C* Driver Version to 3.0.0-Alpha3

---

doc/2_loading.md
doc/6_advanced_mapper.md
project/Versions.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/ColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/PrimitiveColumnType.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DataTypeConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/ColumnTypeSpec.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeSerializationTest.scala

Add SmallIntType case class mapped to java.lang.Short and CQL's "smallint" type
Does this need test coverage?  If there's a basic datatype spec/test somewhere that I should extend, let me know.

SPARKC-269 Support smallint

---

CHANGES.txt
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/SqlRowWriter.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala

VarInt column is mapped to Spark Sql Decimal type, the data needs
be converted to decimal to Catalyst. It also needs to be converted
back to BigInteger when push down the filters to Cassandra.

SPARKC-266 Fixed VarInt Column filter error In Spark SQL

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala

Inorder to allow more extensibility to Spark Classes we will allow other
classes to access the RowReaders built by RowReaderProvider implementing
classes.

Open Visibility on RowReader

---

CHANGES.txt
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnRef.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnSelector.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/ColumnRefSpec.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/ColumnSelectorSpec.scala

Added FunctionCallRefclass as subtype of `ColumnRef` whose goal is to represent functions selections.
https://datastax-oss.atlassian.net/browse/SPARKC-280

SPARKC-280: Added FunctionCallRef

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLClusterLevelSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraCatalog.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLContext.scala

I've had to disable some of the functionality around having a seperate
cluster identifier in TableIdentifier. SPARK-10104 changed Table
Identifier from a Seq[String] to a case class with two members Table and
Database. We've raised an issue and will find a workaround in
SPARKC-289. This commit is designed to have Master back up and running.

SPARKC-287: Upgrade CassandraSqlContext and Catalog to compile v 1.6

---

doc/reference.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala

We've run into several end users who are running Streaming applications
with a keep_alive short enough that a new connection is made every
batch. This ends up causing a lot of stress on the C* cluster and an
unneccessary (and time consuming) slowdown every batch.
To avoid these issues, This patch increases the default keep_alive to
5 seconds. Also warn the user if they use a C* DStream option with a
lower frequency than the batch interval.

SPARKC-228: Warn in Streaming Applications with Small Keep_Alive

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceNoPushdownSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraPrunedFilteredScanSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraPrunedScanSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala

Spark 1.6 adds a overridable method unhandledFilters which causes the
catalyst engine to ignore a set filters that the underlying data source
is exhaustively filtering. All of the filters we push down are absolute
so it is safe to remove all pushed down filters and return remaining
filters back to Catalyst.

SPARKC-291: Single Pass Filtering for Pushdown C*Source DF

---

CHANGES.txt
doc/5_saving.md
doc/reference.md
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WritableToCassandra.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WriteConf.scala

With the current default write consistency level of LOCAL_ONE,
it's relatively easy to overwhelm a cluster because it only waits
for one replica to ack the write before proceeding on.
Changing the default write consistency level to LOCAL_QUORUM means
that it will do a little more natural throttling to allow the cluster to keep up
with the writes for multiple replicas.
It seems like it would make for a more stable out of the box experience.

SPARKC-262: Set write consistency level to LOCAL_QUORUM.

---

CHANGES.txt
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala

The joinWithCassandraTable method was incorrectly making a ReadConf from
default rather than using the SparkConf. The jWCT method now pulls the
sparkConf from the left hand side RDD and uses this for the jWCT
readConf.

SPARK-294: JWCT should inherit Spark Conf from Spark Context

---

project/Settings.scala

Ther move to Spark 1.6rc2 has caused a huge variety of
brokenness inside of the assembly. We have to explicitly drop
poms and such from various jars and use "last" merge strategies
on a variety of classes which are now getting included from multiple
dependencies.
Spark itself is guilty of adding
org/apache/spark/unused/UnusedStubClass.class
To every module

Fix for sbt assembly

---

project/Settings.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala

Prior to this commit, the 1.5 branch could not successfully complete an assembly task for Scala 2.11 due to:
- 4 Failed unit tests
- Unsuccessful merge strategy for assembly
These changes were derived from previous pull requests to the master branch; they are simply making their way into the 1.5 branch. 
There was an additional merge strategy addition that I made which I did not find in prior commits (line 338 in Settings.scala). Deduplication errors were thrown without this. I have successfully tested a 2.11 assembly with these changes.

Assembly fix for 1.5 2.11

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/typeTests/InetTypeTest.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/typeTests/UUIDTypeTest.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/typeTests/VarintTypeTest.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/SqlRowWriter.scala

The type converters are fully capabible of handeling all of the
edge cases for DataFrame -> CassandraType conversions. We can use this
instead of the custom code previously in the SqlRowWriter class. In
addtiion, added test cases for the special matching previously done.

SPARKC-306: Remove Special Matching for Dataframe Writers

---

CHANGES.txt
project/CassandraSparkBuild.scala
project/Settings.scala
project/Versions.scala
spark-cassandra-connector/src/it/resources/cassandra-default.yaml.template
spark-cassandra-connector/src/it/resources/cassandra-password-auth.yaml.template
spark-cassandra-connector/src/it/resources/cassandra-ssl.yaml.template

Upgrade Cassandra version to 3.0.2 by default and allow to specify arbitrary Cassandra version for integration tests through the command line

SPARKC-307: Upgrade Cassandra version to 3.0.2 by default

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/SqlRowWriter.scala

I have encountered a performance issue when 99% of the time was spent getting a type converter in SqlRowWriter, actually the problem was a bit deeper — I needed to make my batches per-replica instead of per-partition, but the point is that, still, cached converters weren't used.

use cached TypeConverter in SqlRowWriter

---

CHANGES.txt
doc/5_saving.md
doc/reference.md
spark-cassandra-connector-java/src/main/java/com/datastax/spark/connector/japi/RDDAndDStreamCommonJavaFunctions.java
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/doc/DocExamples.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/BoundStatementBuilderSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/GroupingBatchBuilderSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/CassandraOption.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/Symbols.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/BoundStatementBuilder.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/ReplicaLocator.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WriteConf.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeConverterTest.scala

Previously unset columns had to be set to null since the Cassandra
Protocol <= V3 did not support unbound parameters in bound statements.
The newere version of the protocol allows for this, and this patch
enables the connector to take advtange of that behavior.
This is done through use of a new option container, CassandraOption.
This class holds an Option and the behavior that a None should have upon
being written. With this class a row can have varying behavior from
column to column and row to row.
If an Unset is used on a C* version prior to Protcol Version 3 a warning
will be logged that the Unset functionality cannot be used and the value
will be treated as a Delete instead.

SPARKC-283: Adds CassandraOption for Skipping Empty Columns

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/NameTools.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala

A new member is added to TableDef isView:Boolean which allows us to
specify whether the shchema represented by the TableDef is a
MaterializedView. We could also refactor the TableDef into multiple
classes but I found this to take considerably more refactoring than just
adding the single element. This allows all 1.5 TableDef code to be
compatible and supports future View Development.
Added a small trap for those trying to write to a Materialized View to
avoid getting a Java Driver Exeception.

SPARKC-326: Support for reading Materialized Views

---

doc/reference.md
project/Settings.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/SparkTemplate.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CustomFromDriverSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/ColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/CustomDriverConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ConfigCheck.scala

Allow for extending the `fromDriverRow` method of columnType. This
extension point should allow for custom cassandra types known by the
driver to be read.

SPARKC-325: Provide an extension for New Driver Types

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/BasicCassandraPredicatePushDown.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/PredicatePushDownSpec.scala

In this patch we add the IndexClassName to the TableDef inorder to use
this information in pushdowns. All though the current C* driver does not
expose indexOptions information at this time it will be needed for
dealing with SASI indexes in the future.

SPARKC-331: Include More Index Information in TableDef

---

CHANGES.txt
doc/14_data_frames.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLClusterLevelSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ConfigParameter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/DataFrameOption.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLContext.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DefaultSource.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/package.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/ConsolidateSettingsSpec.scala

SPARKC-289: Fixed accessing multiple Cassandra clusters from Spark SQL by adding the ability to define cluster/keyspace aliases

SPARKC-289: Fixed accessing multiple Cassandra clusters from Spark SQL

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeConverterTest.scala

Adds type conversion support for `org.joda.time.DateTime` to `com.datastax.driver.core.LocalDate`. Solves  [SPARKC-342](https://datastax-oss.atlassian.net/browse/SPARKC-342)
@RussellSpitzer  @pkolaczk for review

[SPARKC-342] support Joda time for LocalDate type

---

CHANGES.txt
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverterSpec.scala

Allow to save nested optional case class in udt.
Some(caseClass) is save like a caseClass.
None is save like null.
Is a quick fix I thinks it's can be donne in a better way.
ps : Is may be a good idea to replace run time reflection by compile time macro.

[SPARKC-346] - Nested Optional Case Class can be save as UDT

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/SchemaSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala

We store indices definitions in TableDef in order to use them in
predicate push down. As discussed, currently we do not support predicate
push down for custom and collection indices.
This commit drops these kinds of indices for TableDef#isIndexed and
TableDef#indexedColumns methods. Meaning if an index is not targeted at
single column it never participates in an evaluation of a result for
these two methods.
Nevertheless please note that all indices are present in TableDef.
Unused indices eventually are going to be used in predicate pushdown as
well.
To hide this planned changes from users, some of the TableDef properties
are now private.

SPARKC-347 drop indices that can not be used in predicate push down

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeConverterTest.scala

As requested by @pkolaczk (https://datastax-oss.atlassian.net/browse/SPARKC-342), merging this patch also into b1.5  (see #946)

Sparkc 342 support joda time for date type

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DefaultSource.scala

The current message makes it seem as if there is no way to insert to a
C* table if there is data within it. This patch changes the message so
it is clear that the error is because of the save mode and suggests a
workaround if Append behavior was expected.

SPARKC-338-b1.4: Change DF ErrorIfExists Message

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/MultipleRetryPolicy.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/CassandraConnectorConfSpec.scala

Delayed retrying was implemented by Thread.sleep, which was
unfortunately executed by a Netty thread-pool. Blocking that thread pool
may lead to a general lockup of the connector.
Currently, there is no safe way of implementing delayed retries, because
such a feature would have to be implemented in the Java driver.
This change does not introduce API changes. Configuring delayed retrying is
still possible, but will have no effect.

SPARKC-360: Disable delayed retrying

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartition.scala

While <= MinToken wraps and works correctly by itself, when coupled with
a predicate such as "x =1" it fails to wrap. To fix this we just check
that the token(pk) >= MinToken if the partition spans (MinToken,
Mintoken)

SPARKC-368: Cql for SinglePartition Queries needs to use >= MinToken

---

.travis.yml
project/Settings.scala

As we have problems with container based infrastructure (these manifest
themselves as JVM exiting with 137 code). This commit moves travis
builds back to VM infrastructure, to Trusty (with 7.5GB of memory), see:
https://docs.travis-ci.com/user/ci-environment/
Also this commit bumps up parallelism for test execution

SPARKC-367 move back to VM infrastructure

---

.gitignore
CHANGES.txt
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/TupleValue.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DataTypeConverter.scala

Fix support for C* Tuples in Dataframes.
This commit adds conversion methods. C* Tuples are converted to catylyst's StructType with index.toString as name.
TupleValue implements Product to allow catalyst properly iterate over it's values.
Also added some test for RDD and C* Tuples.

Sparkc 357 support for C* Tuples in Dataframes.

---

CHANGES.txt
doc/reference.md
project/SparkCassandraConnectorBuild.scala
project/plugins.sbt
spark-cassandra-connector-perf/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDDBenchmark.scala
spark-cassandra-connector-perf/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDDData.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala

This ought to speed up joining with C* table by using executeAsync
(instead of execute) and prematerializing C* ResultSets during join
operation. Current implementation materializes all ResultSetFutures
and returns iterator that blocks on future's result.
This also adds performance module with jmh plugin. Within module
there is a simple benchmark that was used to generate results 
in one of the following comments.

SPARKC-233 use executeAsync when joining with C* table

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/ReplicaLocator.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala

Refactors all tableDef obtaining operations through tableFromCassandra
which attempts to retreive the given requested table def. If the call
fails, it sleeps for 1 second and retries. On the second failure it
throws an exception reporting that the table could not be found with the
table name recommendations as before. The sleep should be replaced with
a forced schema update once that becomes available in the Java Driver.

SPARKC-379: Retry Schema Checks in case of Java Driver Debounce

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala

Preconditions with indexed columns that belong to partition key but do
not form the whole partition key generate failures.
This kind of queries should be executed as a query with index column
specified, not discarded as a query with incomplete partition key.
This changes CassandraRDDPartitioner#containsPartitionKey so that it
does not throw exception whenever the partition key is incomplete and
all precodition colums are indexed. Other cases for
CassandraRDDPartitioner#containsPartitionKey are not changed.

 SPARKC-348 accept predicates with indexed partition columns

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/GettableData.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeConverterTest.scala

Conversion is added because driver's LocalDate is not
serializable.
GettableData now converts LocalDate to Joda's LocalDate.

 SPARKC-385 add driver.LocalDate conversion

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionedRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/ReplicaPartitioner.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala

Previously the behavior of repartition by Cassandra Replica was random
within the bounds of assigining keys to the the correct replicas. This
meant that multiple application of the partitioner could result with
rows in different partitions even if they share the same partition key.
The new behvaior pulls the token determination and replica determination
into the partitioner. This removes the need for the
"keyByCassandraReplica" function for repartitionByCassandraReplica.

SPARKC-278: Make Repartition by Cassandra Replica Deterministic

---

spark-cassandra-connector-demos/kafka-streaming/src/main/scala/com/datastax/spark/connector/demo/KafkaStreamingScala211App.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/CassandraRunner.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/DynamicCassandraPorts.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceNoPushdownSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
spark-cassandra-connector/src/it/scala/org/apache/spark/sql/CassandraPrunedFilteredScanSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/LocalNodeFirstLoadBalancingPolicy.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/PreparedStatementCache.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionGenerator.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/DataSizeEstimates.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/TokenGenerator.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/AnyObjectFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/CqlWhereParser.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/Logging.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/SerialShutdownHooks.scala

Spark 2.0 moves the logging trait to be fully internal this means the
connector can no longer use it. To avoid conflicts we extract the trait
as we were using it so that the 1.6 and future versions of the connector
will work with Spark 2.0.

SPARKC-390: Replace org.apache.spark.Logging with internal Logging Trait

---

doc/2_loading.md

On line 286, `joinWithCassandra` should be `joinWithCassandraTable`.

Corrected minor issue in example code

---

project/Versions.scala

We have had some incompatibilities with Spark 1.5.2 when building the connector against 1.5.1. Changing the build target for b1.5 to 1.5.2

Upgrade b1.5 to Spark 1.5.2

---

CHANGES.txt
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/AbstractCassandraJoin.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala

This a rebased version (so to compile against the latest version of the connector) of https://github.com/datastax/spark-cassandra-connector/pull/832
Like https://github.com/datastax/spark-cassandra-connector/pull/832 there is quite a lot of code duplication. Unlike https://github.com/datastax/spark-cassandra-connector/pull/832 it relies on executeAsync for better performance.

SPARKC-181 -Adding support for left joins

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableRowReaderProvider.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraRDDPartitioner.scala

Previously the split_size parameter was an Integer and was computed by
multiplying split_size_in_mb * 1024 * 1024 which will overflow for
values greater than 2047. Changing this to a Long moves this threshold
to 2097152. Hopefully in 10 years I'll look back and say what a small
amount of ram, 2TB per spark partition.

SPARKC-413: Avoid overflow on SplitSizeInMB param

---

spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/PredicatePushDown.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/PredicatePushDownSpec.scala

Timeuuids are compared differently in Spark and in Cassandra. In
Cassandra Timeuuids are compared bas on the Time portion of the binary
data. In Spark they are compared lexically (in byte order). In Spark <
1.6 all filters in Dataframes are applied twice, once at the DataSource
and once in Spark. This double application would be done using both of
the above comparitors leading to incorrect results. We will now throw
exceptions if we sense an end user is trying to perform one of these
impossible comparisons.

SPARKC-405: Disallow TimeUUID Predicate Pushdown

---

spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/BasicCassandraPredicatePushDown.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/PredicatePushDownSpec.scala

Throws an exception when trying to do a Spark(lexical) comparison on a TimeUUID, but allows comparisons if C* handles the entire comparison(Compared based on time).

SPARKC-405: B1.6

---

README.md
doc/developers.md
project/Settings.scala
project/SparkCassandraConnectorBuild.scala
project/Versions.scala
project/plugins.sbt

182174b (Russell Spitzer, 3 minutes ago)
SPARKC-355: Add shadedConnector Project
Adds an additional project which mirrors the normal connector build project
except it marks ALL libraries except those we are explictly shading as
provided. This makes it so it's assembly task will only include the shaded
jars we want and no other dependencies.
This assembly task which only includes shaded deps is then set as the
assembly target of spPackages which in coordination with spShade changes
the spDist task to use the shaded assembly jar as it's target rather than
the standard assembly jar with all dependencies.
3a8947a (Russell Spitzer, 2 hours ago)
SPARKC-355: Explicitly use netty-all at a specified version
To add a bit more explictness to our build, all netty sub components are
excluded and …

SPARKC-355: Shade guava and include the Cassandra Java Driver in public distributions

---

README.md
doc/developers.md
project/Settings.scala
project/SparkCassandraConnectorBuild.scala
project/Versions.scala
project/plugins.sbt

High Level Summary:
Cassandra Java Driver and Shaded Guava are in the release artifacts
No Shaded Netty (Did not seem to conflict)
Package, Publish* tasks push shaded artifacts
Details
This patch publishes artifacts as a jar with the Cassandra
Java Driver included and guava shaded. This is a necessity because of
guava conflicts in Spark 2.0. Essentially any references to Guava that
the driver uses must be to a Guava version greater than 16. We
accomplish this by shading all references within the driver which we
also include. This makes it impossible to change the C* java driver
used with the connector. This is not a large issue because any Cassandra
Java Driver without shaded guava on the  classpath will throw incompatible guava errors.
To distribute this artifact the connector project …

SPARKC-355: Have all public artifacts use the Shaded Jar

---

doc/FAQ.md
project/SparkCassandraConnectorBuild.scala

Changed the `full` project to `unshaded` to more clearly indicate that
the package is unshaded.

SPARKC-420: Publish Unshaded Artifacts

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/PartitionedCassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/ReplicaPartitioner.scala

Tokens might give Integer.MIN_VALUE as hashcode. This will lead to a negative
index into the set of replicas for the corresponding key and fail the task.
The reason is that Math.abs() returns a negative value for Integer.MIN_VALUE
and % gives a negative result in case the dividend is negative.
To fix this the partitioner now applies Math.abs() to the result of the modulo
calculation instead of to the token hash (the dividend). This guarantees that
the index is never negative.

SPARKC-419: Fix partitioner on Integer.MIN_VALUE

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala

`InetAddress.getLocalHost.getHostAddress` fails in certain environments, so it cannot reliably be used as a default value for the hostsStr.
See the following StackOverflow post for an example of this occurring in the wild: http://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception
Our temporary solution is to add the address that this generates to `/etc/hosts`.

Use ConnectionHostParam.default as the default hosts string.

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/DataFrameFunctions.scala

Give a useful error message when creating a table and a column specified
to be a partition key or clustering key cannot be found. Previously the
user would get a criptic error on a None type.

SPARKC-428: Better error messages on CreateCassandraTable from DataFrame

---

project/Settings.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala

JoinWithCassandraTable places limit and order queries in the wrong
order. Thanks to bryanventeicher@gmail.com for pointing this out.

SPARKC-433: Correct order of "Limit" and "orderBy" clauses in JWCT

---

CHANGES.txt
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala

The coalesce method looks more convinient to specify the number of paritions than ReadConf usage.

SPARKC-161: RDD coalesce() pushdown to cassandra.

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraPredicateRules.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DefaultSource.scala

Previously we removed all options to be passed through to the
CassandraSource that were not defined in the connector. This made it
impossible for a user supplied pushdown class to use per Table options
or Spark Conf settings.
This commit also breaks the custom pushdown rules api by passing through the
consolidated SparkConf which includes TableOptions and the Spark Conf.

SPARKC-435: Allow Custom Conf Options for CustomPushdowns

---

CHANGES.txt
README.md
doc/5_saving.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CustomFromDriverSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/streaming/RDDStreamingSpec.scala
spark-cassandra-connector/src/main/java/com/datastax/spark/connector/japi/RDDJavaFunctions.java
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/ColumnSelector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/AbstractCassandraJoin.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/ColumnType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/CustomDriverConverter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WritableToCassandra.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DataTypeConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/testkit/SparkCassandraFixture.scala

Backports of the following tickets to B1.6:
SparkC-181 (left join)
SparkC-349 (deleteFromCassandraTable)
SparkC-440 (CustomDriverConverter)
EDIT - 
Added SparkC-443 backport

B1.6 Backports

---

project/Versions.scala

1.8.0 of has a known vulnerability. It is patched in 1.9.3

SPARKC-457: Upgrade CommonsBeanUtils to avoid SID-760

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala

The current code assumes that if you are converting a UDT in a
collection or some other nested structure that all subclasses can be
loaded on the same classloader than the SCC has been loaded on. For some
runtime enivronments (like DSE) this is not true and the SCC is on a
different classloader than the application code. This can lead to the
lookup on the contained class failing with a ClassNotFound Exception.
To avoid this situation we allow for the first class (which will be
tuned to the correct classloader in it's runtime mirror) to force
all sub-converters created to enable it's construction to be built
with the same Classloader.
This fixes situations like
case class Row(k: Int, v: Seq[UdtCaseClass])
so that
The Classloader which loads "Row" will be used to load "UdtCaseClass".
A Test …

SPARKC-363: Find Converters for Classes on Different Classloaders

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/RefCountedCache.scala

If set up a remote C* cluster and submit a job from spark cluster to
connect to remote C* cluster. The CassandraConnectorConf is serialized
and deserialized into different CassandraConnectorConf object for
the same original CassandraConnectorConf. Then each time sessionCache
creates new session for each deserialized CassandraConnectorConf.
Too many new sessions results too many cluster objects, and the
following errors are found.
ResourceLeakDetector: LEAK: You are creating too many HashedWheelTimer instances
To fix the issue, we change sessionCache key from CassandraConnectorConf
to String which is the serialized CassandraConnectorConf in String format.
The second issue is acquire method of RefCountedCache is not synchronized.
Even the cache itself is TriMap, the acquire method still …

SPARKC-441 Fix CassandraConnector sessionCache remote and race condition

---

doc/3_selection.md
project/Versions.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/EmbeddedCassandra.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/RDDSpec.scala
spark-cassandra-connector/src/main/java/com/datastax/spark/connector/japi/RDDJavaFunctions.java
spark-cassandra-connector/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDD.java
spark-cassandra-connector/src/main/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDD.java
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/package.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/AbstractCassandraJoin.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLimit.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/EmptyCassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/CassandraStreamingRDD.scala
spark-cassandra-connector/src/test/java/com/datastax/spark/connector/japi/rdd/CassandraJavaPairRDDTest.java
spark-cassandra-connector/src/test/java/com/datastax/spark/connector/japi/rdd/CassandraJavaRDDTest.java

c2f1cdb (Russell Spitzer, 6 minutes ago)
SPARKC-446: Enable PerPartitionLimit as a CassandraRDD Function
Cassandra 3.6 enables PerPartitionLimit. To accesses this the underlying
CassandraRDD limit field now holds a `CassandraLimit` opition. There are
two possible values at the moment.
SparkPartitionLimit - Which limits the number of rows returned per Spark
Partition CassandraPartitionLimit - Which limits the number of rows
returned per Cassandra Partition
They are accessed through the same api as previously existed
CassandraRDD.limit() - Sets the SparkPartitionLimit like previously
CassandraRDD.perPartitionLimit - Sets the CassandraPartitionLimit
ce8ea46 (Russell Spitzer, 6 minutes ago)
SPARKC-446: Change Cassandra Version to 3.6
Only 3.6 Supports Per Partition Limit

SPARKC-446 Enabling PerPartitionLimits for CassandraTable and JoinWithCassandraTable

---

.travis.yml
doc/reference.md
project/Testing.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CustomTableScanMethodSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/SessionProxy.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ConfigCheck.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/ReadConfTest.scala

Write a message for this pull request. The first block
of text is the title and the rest is the description.
Changes:
550eed4 (Russell Spitzer, 2 minutes ago)
SPARKC-459: Creation of CustomTableScan Extension Point
Users can now extend the CustomTableMethod trait to provide a new method of
executing statements. The given method is passed in via classname in the
SparkConf.
08d95e9 (Russell Spitzer, 2 hours ago)
SPARKC-459: Allow for a different Session Interface in SessionProxy
Previously the interface of Session proxy was always the default OSS
Datastax Driver session. A new connection parameter is added
spark.cassandra.connection.session_interface which lets an end user specify
a different session interface to be used.
e905ccb (Russell Spitzer, 3 hours ago)
SPARKC-459: Seperate Execute …

Requesting a pull to datastax:master from datastax:SPARKC-459

---

project/Settings.scala

Previously the Guava 16.0.1 shading was missing the thirdparty package
within the library. This caused conflicts with user applications that
were importing their own copy of Guava 16.0.1. Correctly shading the
library should fix this issue.

SPARKC-461: Fix Incomplete Shading of Guava

---

README.md
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala

Changes:
89bdff2 (Russell Spitzer, 81 seconds ago)
SPARKC-462: Publicly display minimum Java Target Versions
Readme version table now has Java and Scala Version Info.
489cf89 (Russell Spitzer, 11 minutes ago)
SPARKC-462: Remove Java8 Dependency in CassandraConnectorConf
While we internally had decided to target Java8 in 1.6 we did not publiclly
announce this. To keep Java7 Compatibility we will roll back the use of
Java8 Classes.

Requesting a pull to datastax:b1.6 from datastax:SPARKC-462

---

doc/reference.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/DataFrameFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/SparkContextFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/DStreamFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/streaming/StreamingContextFunctions.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/WritableToCassandra.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/CassandraConnectorConfSpec.scala

We will boost up the number of CassandraDriver Connections based
on the number of cores allocated to the machine. The user will also be
able to force a parameter for this value. This can be changed at runtime
so we will set it at the creation time of the RDD based on the driver's
information at that time.

SPARCK-471: Automatic Adjustment of Max Connections

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/CassandraRow.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/FunctionBasedRowReader.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/ValueRowReader.scala

SPARKC-383 added a cache of codecs so reads would not look up codecs for
every row. This patch extends that so that all RowReaders will use the
cache instead of just some.

SPARKC-473: Always use the codec Cache when reading from Driver Rows

---

CHANGES.txt
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/CassandraRow.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/FunctionBasedRowReader.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/ValueRowReader.scala

SPARKC-383 added a cache of codecs so reads would not look up codecs for
every row. This patch extends that so that all RowReaders will use the
cache instead of just some.

SPARKC-472-b1.6 Always use the codec cache when reading from Driver Rows

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CustomTableScanMethodSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Scanner.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala

The original implmentation of the CustomScanMethod made it difficult to
extend the functionality inside of CassandraTableScan RDD since it
provided no ability to perform a "close" action on termination. This
meant external users were unable to properly cleanup their
implementations.
To fix this we change getScanMethod to getScanner which returns a
Scanner object which provides two methods, Scan and Close. One Scanner
is built per Spark Partition so the the initializer will only be called
once per Spark Partition and the close method only once at task
Completion.

SPARKC-481: Refactor Custom Scan Method

---

doc/FAQ.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDMockSpec.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/CassandraRDDMock.scala

The CassandraRDDMock just passes through another RDD and pretends it is
a CassandraRDD.

SPARKC-466: Add a CassandraRDDMock for end users to use in Unit Testing

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/RowWriterFactory.scala

Previously when a DataFrame was turned into an RDD by it's `rdd` method
saveToCassandra and joinWithCassandraTable would fail because of the
lack of an implicit RowWriterFactory. To fix this we add an implicit
for a RowWriterFactory for RDD[T <: Row] which ends up mapping to the
SqlRowWriterFactory which we already have written.

SPARKC-475: Add implicit RowWriterFactory for RDD[Row]

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/mapper/DefaultColumnMapper.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala

Previously we were overly strict on checking whether a write was
valid. A Cassandra Table can be written too with only Partition Keys and
Static columns if no clustering columns are included. We ease the check
in TableWriter by only requiring the partition key if all other columns
are Static Columns.

SPARKC-470: Allow Writes to Static Columnns and Partition Keys

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionGeneratorSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/SplitSizeEstimator.scala

9e4c3c9 (Russell Spitzer, 4 days ago)
SPARKC 492: Protect against Size Estimate Overflows
```scala val tokenRangeSizeInBytes = (totalDataSizeInBytes /
ringFraction).toLong
```
In datasize estimates has the possibility of overflowing when getting the
size_estimates from a datacenter whose primary range contains a very tiny
range BUT still also contains data. In these cases a tiny size in bytes
will be divided by a miniscule range fraction leading to a huge value. This
when converted toLong becomes Long.MaxValue.
When these situations arise our size_estimates are no longer reliable so we
need to fall back to a safer estimate. In 2.0 we can use the min Spark
Nodes * 2 + 1 but in 1.6 we don't have that information. To keep our
changes small, here we will just use the endpoints present in the …

Requesting a pull to datastax:b2.0 from datastax:SPARKC-492-b2.0  Changes:

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionGeneratorSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/CassandraPartitionGenerator.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/Murmur3PartitionerTokenRangeSplitter.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/RandomPartitionerTokenRangeSplitter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/partitioner/RandomPartitionerTokenRangeSplitterTest.scala

```scala
val tokenRangeSizeInBytes = (totalDataSizeInBytes /
ringFraction).toLong
```
In datasize estimates has the possibility of overflowing when
getting the size_estimates from a datacenter whose primary range
contains a very tiny range BUT still also contains data. In these
cases a tiny size in bytes will be divided by a miniscule range
fraction leading to a huge value. This when converted toLong becomes
Long.MaxValue.
When these situations arise our size_estimates are no longer
reliable so we need to fall back to a safer estimate. In 2.0 we can
use the min Spark Nodes * 2 + 1 but in 1.6 we don't have that
information. To keep our changes small, here we will just use the
endpoints present in the target datacenter * 2 + 1.

SPARKC 492: Protect against Size Estimate Overflows

---

README.md

Added link to the Slack channel
- blanks were removed automatically after saving the changes for slack in Atom (and thought it'd be nice to have them too)

Link to spark-connector Slack channel at DataStax Academy Slack

---

README.md
doc/1_connecting.md

Just few markdown changes for docs formatting. Two are very important to activate the slack link and section header.

[DOCS][MINOR] Formatting

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TimestampParser.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/types/TypeConverterTest.scala

timestamp has one, to have a consistent story the date parser is added

DSP-12259: add support for date string parsing

---

spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/CassandraRunner.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/EmbeddedCassandra.scala
spark-cassandra-connector/src/it/resources/log4j.properties
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/partitioner/ReplicaPartitionerSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/partitioner/TokenGeneratorSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/ReplicaPartitioner.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/TokenGenerator.scala

Previously endpoints were being calculated with the wrong ByteBuffer.
They needed to use the routing key but were using the Token buffer
instead. To fix this we change the buffer which was passed in to the key
buffer instead.
To fully test this the embedded cassandra class is extended so that it
can create a multi-node cluster. This is then used to make sure or
replica partitioner is accurately dividing nodes by replica and evenly
distributing the keys.

SPARKC-485: Fix ReplicaPartitioner Endpoint Call

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/LocalNodeFirstLoadBalancingPolicy.scala

Shuffling a set doesn't actually do anything so this would end up giving
the rest of the hosts in order regardless of the shuffle.
Problem found and fix written by Loki Coyote @lokkju on Github

SPARKC-496: Fix Shuffling of a Set in Local Node FirstPolicy

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/ThrottlingSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/AsyncExecutor.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/QueryExecutor.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/writer/AsyncExecutorTest.scala

A change in the Cassandra Java driver has caused the executeAsync method
to become fully asynchronous. This means that executeAsync calls can
sometimes return an exception of BusyPoolException, meaning that queries
were issued and no open execution pathway could be found. These
exceptions are always retryable because they indicate the local driver
state is temporarly busy. So we will retry these exceptions.
To make sure we don't have too many retries we will also make sure to
limit the number of max concurrent requests to the current
"requestsPerConnection" as specified in the pooling options. We are
already setting the maxPool size to the number of cores per executor so
this should prohibit having more requests in flight than we have open
connections.

SPARKC-503: Retry PoolBusy Exceptions, Throttle JWCT Calls

---

doc/11_metrics.md
spark-cassandra-connector/src/main/scala/org/apache/spark/metrics/CassandraConnectorSource.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/metrics/OutputMetricsUpdater.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/metrics/OutputMetricsUpdaterSpec.scala

I added a histogram only for row count. If needed I can easily add similar histograms for bytes written, duration, even wait times.

SPARKC-501: added a histogram which records the distribution of the rows in batches

---

doc/reference.md
project/SparkCassandraConnectorBuild.scala
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/driver/core/PreparedIdWorkaround.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/CassandraRow.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/MultipleRetryPolicy.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/AbstractCassandraJoin.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/MultipleRetrySpec.scala

Changes our retry policy to retry all exceptions which can possible be
temporary. This will move burden to users to detect when the system is
beyond hope but will allow a momentarily troubled cluster recover from
issues.

SPARKC-507: Infinite Retries

---

doc/reference.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/driver/core/PreparedIdWorkaround.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/CassandraRow.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/MultipleRetryPolicy.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/AbstractCassandraJoin.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/QueryExecutor.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/MultipleRetrySpec.scala

Changes our retry policy to retry all exceptions which can possible be
temporary. This will move burden to users to detect when the system is
beyond hope but will allow a momentarily troubled cluster recover from
issues.
Some queries will not be retried regardless of the retry policy. To fix
this we mark all of our idempotent queries so the driver will retry
them.

SPARKC-507: Infinite Retries and  Mark all Idmepotent Queries

---

doc/reference.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/driver/core/PreparedIdWorkaround.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/CassandraRow.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/MultipleRetryPolicy.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/AbstractCassandraJoin.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/QueryExecutor.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/cql/MultipleRetrySpec.scala

Write a message for this pull request. The first block
of text is the title and the rest is the description.
Changes:
885c7862 (Russell Spitzer, 30 minutes ago)
SPARKC-507: Change Async Method in JoinWithCasasndraTable
New concurrent.reads parameter allows users to limit read paralleism in the
same way they could limit write parallelism. This is only applied to
concurrent requests during direct join point lookups.
Previously joinWithCassandraTable would issue all futures using a toList
operation on the query iterator. This would end up putting all of the
futures in memory causing OOM if there were many keys in the partition.
To fix this we remove the list call and instead use a sliding iterator
which will always be pulling new futures from the iterator.
f95f84ba (Russell Spitzer, 3 hours …

Requesting a pull to datastax:master from datastax:SPARKC-507-master

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverter.scala
spark-cassandra-connector/src/test/java/com/datastax/spark/connector/mapper/ClassWithUDTBean.java

Previously a null would hit trigger a `CannotConvert` error before
getting to the "nulls allowed" check in gettable mapped data. Now we
attempt to pass through the null and catch the exception if we cannot
cast the Null into the acceptable type.

SPARKC-426: Allow POJOS to be set as NULL

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/TypeConverter.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/rdd/reader/GettableDataToMappedTypeConverterSpec.scala

053d77c9 (Russell Spitzer, 55 seconds ago)
SPARKC-318: Removed unused function
This function was added in the initial PR but doesn't seem to be used
anywhere. I've removed it and all the tests still pass.
aab13f58 (Nick Rushton, 1 year, 5 months ago)
Add tests for SPARKC-318 Fix mapping a column with null value
22ad959e (Delyan Dimitrov, 1 year, 6 months ago)
Fix mapping a column with null value

SPARKC-318: Nested columns in an MBean cannot be null

---

doc/reference.md
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/ReadConf.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DefaultSource.scala

Previous to this it was impossible to choose the target split count for
a CassandraSourceRelation (SparkSql, Dataframes). This patch allows
for case insensitive parameter passing as well as adding a new parameter
for `splitCount`. The extra lowerCase in `consolidateConfs` is for
making the forward merge easier.

SPARKC-527: Allow Split Count to be Passed to CassandraSourceRelation

---

project/plugins.sbt

Scalaz version used by previous version of that plugin wasn't compatible with sbtclipse
plugin, so bumping version of sbt-coursier plugin that uses newer version of scalaz,
resolved the issue

Bump version of sbt-coursier plugin

---

doc/reference.md
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/test/scala/org/apache/spark/sql/cassandra/ConsolidateSettingsSpec.scala

Previously, parameters set in the SqlConf via "SET ? = ?"
required setting cluster/parameter. With default/parameter
being the catch all for non specific clusters. In this patch
we allow setting a parameter without any cluster prefix.

SPARKC-531: Allow non-cluster prefixed options in sqlConf

---

doc/reference.md
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/CqlWhereParser.scala
spark-cassandra-connector/src/test/scala/com/datastax/spark/connector/util/CqlWhereParserTest.scala

Previous non greedy match would StackOverflow on long string literals.
New version does not.

SPARKC-532: Change Str Literal Match to Be Greedy

---

doc/5_saving.md

GitHub Markdown requires a space between `#` and the header.

Fix header formatting

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/writer/TableWriterSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala

DSE includes a virtual column "solr_query" which was used for
interacting with Solr in DSE. This column cannot actually be written too
so we should remove references to the column when writing.

SPARKC-541: Ignore Solr_query when setting up Writing

---

project/Versions.scala
spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/YamlTransformations.scala
spark-cassandra-connector/src/it/resources/cassandra-3.11.yaml.template
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala

A previous change to deal with the CaseInsensitiveMap in Spark 2.2
caused issues for users of Spark 2.0 which behaves slightly differently
in passing it's map of operation specific parameters to the Datasource.
To avoid issues we will check for both mixed-case and lower-cased
versions of all properties.
In addition I updated the C* test version so that it will work with more
modern Java runtimes.

SPARKC-551: Fix CassandraSourceRelation Option Parsing in Spark 2.0

---

spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/PreparedStatementCache.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/SessionProxy.scala

Previously the case matching in the SessionProxy incorrectly stated that
the RegularStatement class was a String, this meant that Regular
Statements would never actually get matched. To fix this we correct the
class type and in addition we add some tests to actually check the
cache. This still can't avoid all reprepares since the TrieMap is a "at
least once" guarentee and can generate extra calls sometimes.

SPARKC-558: RegularStatements not Cached by SessionProxy

---

spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/YamlTransformations.scala

Loading from the system ClassLoader makes unnecessary (and in my situation, incorrect) assumptions about the classpath hierarchy.
It is more reliable to stick with the ClassLoader that loaded this class (and thus the spark-cassandra-connector-embedded Jar)

Load Yaml Template from Proper ClassLoader

---

doc/15_python.md

Fix the hyperlink to save modes in the latest Spark documentation

Fix the hyperlink to save modes in the latest Spark documentation

---

connector/src/it/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinSpec.scala
connector/src/main/scala/com/datastax/spark/connector/CassandraSparkExtensions.scala
connector/src/main/scala/com/datastax/spark/connector/DseSparkExtensions.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/DsePredicateRules.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinExec.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala
connector/src/test/scala/com/datastax/spark/connector/embedded/SparkTemplate.scala
doc/14_data_frames.md
doc/reference.md

The DS Merge brought in a few parameters for DSE Specific features which
didn't follow the spark.cassandra pattern of everything else. We changed
all the parameters which don't work specifically with dse to generic
spark.cassandra.
Options for Datasource Tables exclusively are also moved into their own
section.

SPARKC-575: Change Dse Prefixed Parameters

---

connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
connector/src/main/scala/com/datastax/spark/connector/DatasetFunctions.scala
doc/14_data_frames.md
doc/5_saving.md
driver/src/main/scala/com/datastax/spark/connector/cql/Schema.scala
driver/src/test/scala/com/datastax/spark/connector/cql/TableDefSpec.scala

Generate a CQL Create Table statement using a DataFrame and all the parameters required to
construct the CREATE Table statement, like, `IF NOT EXISTS`, `WITH CLUSTERING ORDER BY`,
etc.

[SPARKC-524] Generate a CQL Create Table from DataFrame with options

---

project/Dependencies.scala
project/Versions.scala

As it is not used in SCC and it's transitive dependencies
cause ERRORs during spark-submit bootstrap (only when executed
with --packages argument).

SPARKC-599 exclude org.apache.tinkerpop

---

connector/src/main/scala/com/datastax/bdp/spark/ContinuousPagingScanner.scala
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala

The new exception informs users about possible solutions for
"too many continuous paging sessions are already running"

SPARKC-602 meaningful exception for exceeded max CP session

---

connector/src/main/scala/com/datastax/bdp/spark/ContinuousPagingScanner.scala
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala

The new exception informs users about possible solutions for
"too many continuous paging sessions are already running"

SPARKC-602 meaningful exception for exceeded max CP session 

---

connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogNamespaceSpec.scala
connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogSpecBase.scala
connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogTableReadSpec.scala
connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogTableSpec.scala
connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogTableWriteSpec.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/CassandraCatalog.scala

The CatalogPlugin requires the actual name in name() as it is
used in matching with spark.sql.catalog.<name> setting.

SPARKC-598 return proper name of the catalog

---

build.sbt
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/CcmConfig.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/mode/StandardModeExecutor.scala

remove this workaround once C* 4.0.0 is released

SPARKC-615 temp workaround for inconsistent C* versioning

---

connector/src/it/scala/com/datastax/spark/connector/cql/ContinuousPagingScannerSpec.scala
connector/src/main/scala/com/datastax/bdp/spark/ContinuousPagingScanner.scala
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala

Reintroduce ContinuousPaging throttle configuration properties.
Before this change the properties were silently ignored, this was a side
effect introduced by the Huge Java Driver Refactoring.

SPARKC-606 honor ContinuousPaging properties

---

connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala
connector/src/it/scala/com/datastax/spark/connector/rdd/reader/PrefetchingResultSetIteratorSpec.scala
connector/src/main/scala/com/datastax/bdp/util/ScalaJavaUtil.scala
connector/src/main/scala/com/datastax/spark/connector/cql/Scanner.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/CassandraInJoinReaderFactory.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraCoGroupedRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraMergeJoinRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/reader/PrefetchingResultSetIterator.scala
connector/src/main/scala/com/datastax/spark/connector/util/Threads.scala
connector/src/main/scala/com/datastax/spark/connector/writer/RichStatement.scala
driver/src/main/scala/com/datastax/spark/connector/CassandraRow.scala

The iterator tries to prefetch the next result page. Once the
current page is exhausted, the next page (hopefully
materialized at this point) becomes the current page and a
fetch request is sent.
fetchSize argument was removed, the supplied statement should
have pageSize parameter set by the caller.

SPARKC-619 restore PrefetchingResultSetIterator 

---

connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala
connector/src/it/scala/com/datastax/spark/connector/rdd/reader/PrefetchingResultSetIteratorSpec.scala
connector/src/main/scala/com/datastax/bdp/util/ScalaJavaUtil.scala
connector/src/main/scala/com/datastax/spark/connector/cql/Scanner.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraCoGroupedRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraLeftJoinRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraMergeJoinRDD.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/reader/PrefetchingResultSetIterator.scala
connector/src/main/scala/com/datastax/spark/connector/util/Threads.scala
connector/src/main/scala/com/datastax/spark/connector/writer/RichStatement.scala
driver/src/main/scala/com/datastax/spark/connector/CassandraRow.scala

The iterator tries to prefetch the next result page. Once the
current page is exhausted, the next page (hopefully
materialized at this point) becomes the current page and a
fetch request is sent.
fetchSize argument was removed, the supplied statement should
have pageSize parameter set by the caller.

SPARKC-619 restore PrefetchingResultSetIterator

---

connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
connector/src/main/scala/com/datastax/spark/connector/util/ClassLoaderCheck.scala

During shutdown hive-exec (used in spark-sql) closes context class
loader that was used to load all the SCC classes.
This happens before shutdown hooks invocation. It results in errors
when an additional SCC/Java Driver/Netty class needs to be loaded
during shutdown hook execution.
Unfortunately the class loading errors cause our hook to hang forever
(we use the hook to close all the remaining Driver sessions and
session.close() invocation simply doesn't ever return).
Since there is no way to avoid class loader closing, we need to fix
things on our end.
This PR introduces a workaround for this problem. An attempt to load
a marker class is made just before the shutdown hook invocation. In
case of an error the process exits without calling `close` on the
remaining sessions.
The proper …

SPARKC-620 closed classloader workaround

---

connector/src/main/scala/com/datastax/spark/connector/datasource/CassandraScanPartitionReaderFactory.scala
project/Versions.scala

rowReader is referenced for each row, having a `def` in it's definition
caused new object creation for each row.
Keeping rowReader as val fixes this issue. This changes fullTableScan
perf test time back to normal (from 13 hours(!) to 15 minutes).

SPARKC-614 fix full table scan perf tests

---

connector/src/it/scala/org/apache/spark/sql/cassandra/execution/JoinThrottlingSpec.scala
connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraJoinRDD.scala
connector/src/test/scala/com/datastax/spark/connector/embedded/SparkTemplate.scala

Before this change each maybeSleep was invoked on a new instance
of the RateLimiter which broke throttling.

 SPARKC-627 fix join rowsPerSec throttling 

---

connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala

Apparently we already have a mechanism to wait for the auth
clusters to be ready. As the Auth tests still fail occasionally
this commit extends the await period.

SPARKC-609 extend await time for auth clusters

---

project/build.properties
spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/util/ConfigCheck.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/DefaultSource.scala

Custom connection factories are allowed to provide a set of custom
supported properties. These properties were omitted when provided
as a custom cluster setting (myCluster/my.custom.setting=cp2077).
This commit introduces custom connection properties support for
per-cluster settings.

 DSP-21510 fix per cluster settings with factory custom props

---

connector/src/main/scala/com/datastax/spark/connector/datasource/CassandraTable.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/CasssandraDriverDataWriterFactory.scala
connector/src/main/scala/com/datastax/spark/connector/writer/TableWriter.scala

Each tableFromCassandra invocation results in a metadata
refresh. The operation may be costly.
This PR reduces the number of metadata refresh operations
by making tableDef lazy and reusing available TableDef in
TableWriter.

SPARKC-633 minimize C* metadata refresh count

---

connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectorConf.scala

When CassandraConnector is instantiated with `CassandraConnector(SparkContext)`, config deprecations are not checked (nor automatically replaced).
This is an issue when using any Cassandra RDD function because every default implicit `CassandraConnector` in class `RDDFunctions` is instantiated this way.
For example, when first executing `rdd.saveToCassandra(keyspaceName, tableName, columns, WriteConf())` with no implicit `CassandraConnector` already initialized, then config deprecations are not checked, nor replaced, and deprecated configs are not taken into account.
Note that config deprecations are however checked from methods `ReadConf.fromSparkConf()` and `WriteConf.fromSparkConf()`, so the issue only occurs if these methods are not called previously.
`CassandraConnectorConf` can be …

SPARKC-641 Config deprecations are not checked when instantiating CassandraConnector

---

connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnectionFactory.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
driver/src/test/scala/com/datastax/spark/connector/cql/MultiplexingSchemaListenerTest.scala

Custom connection factories are allowed to provide a set of custom
supported properties. These properties were omitted when provided
as a custom cluster setting (myCluster/my.custom.setting=cp2077).
This commit introduces custom connection properties support for
per-cluster settings.
Test factories are top level objects (not mocks, not inner classes)
because they have to be findable by SCC reflection mechanism.

SPARKC-635 fix per cluster settings with custom props

---

connector/src/it/scala/com/datastax/spark/connector/cluster/Fixtures.scala
connector/src/it/scala/com/datastax/spark/connector/rdd/ReplicaRepartitionedCassandraRDDSpec.scala
connector/src/main/scala/com/datastax/spark/connector/RDDFunctions.scala
connector/src/main/scala/com/datastax/spark/connector/cql/CassandraConnector.scala

`repartitionByCassandraReplica` relocates data to the local(-host) node only, whereas it should relocate data over all the nodes of the local DC instead.
When running `repartitionByCassandraReplica` on a machine where:
- a local node exists, then it relocates the entire data to this single node.
- no local node exist (e.g. with nodes being on remote machines, or with a containerized node with an isolated IP on the local machine), then it always returns an empty RDD without throwing any exception.
The problem is caused by the [reconfiguration](https://github.com/datastax/spark-cassandra-connector/commit/3f891f8c25283eb5fb19eac4407d847d5c8d8d94) of `CassandraConnectorConf` that handles new non-IP-based `ContactInfo`, as part of the v2.5.0 pre-release.
In order to determine the local DC …

SPARKC-642 repartitionByCassandraReplica relocates data to the local node only

---

connector/src/it/scala/com/datastax/spark/connector/rdd/ReplicaRepartitionedCassandraRDDSpec.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/mode/StandardModeExecutor.scala

ReplicaRepartitionedCassandraRDDSpec based on TwoNodeCluster was not
working for DSE 6.8 as this db version relies on metadata dir.
Before this change the metadata dir was shared among
all the nodes in the cluster (which caused Gossip failures that
eventually lead to test failure).
After this change all the nodes in the cluster use separate
metadata dirs.
Additionally, autoboostrapping is now enabled as all the nodes in
TwoNodeCluster need to have data from relevant parts of the token
ring.

SPARKC-642 fix TwoNodeCluster integration test setup

---

connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala
driver/src/main/scala/com/datastax/spark/connector/UDTValue.scala
driver/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala

Slow UDTValue related work on saving to Cassandra:
saveToCassandra for 100K rows (about 100Mb) with cores = 1 (1 Spark thread) took 45 seconds
the UDT has about 50 fields.
spark.cassandra.output.batch.size.bytes = 63000
spark.cassandra.output.concurrent.writes = 160
scala case classes were used for both row and a UDT field.
the same results for Java Beans.
asyncprofiler showed that the recalculation of 'metadata' (CassandraRowMetadata) in com.datastax.spark.connector.UDTValue for each row is burning CPU, because metadata is not reused.
At the same time there is a (unused?) class com.datastax.spark.connector.japi.UDTValue that receives CassandraRowMetadata as a constructor parameter.
I decided to align the approaches in those UDTValue classes. 
Unit tests were not executed. The jar …

SPARKC-647 UDTValue performance fix - reuse CassandraRowMetadata instead of building it for each row (b2.5)

---

spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/UDTValue.scala
spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala
spark-cassandra-connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSQLRow.scala

Slow UDTValue related work on saving to Cassandra:
saveToCassandra for 100K rows (about 100Mb) with cores = 1 (1 Spark thread) took 45 seconds
the UDT has about 50 fields.
spark.cassandra.output.batch.size.bytes = 63000
spark.cassandra.output.concurrent.writes = 160
scala case classes were used for both row and a UDT field.
the same results for Java Beans.
asyncprofiler showed that the recalculation of 'metadata' (CassandraRowMetadata) in com.datastax.spark.connector.UDTValue for each row is burning CPU, because metadata is not reused.
At the same time there is a (unused?) class com.datastax.spark.connector.japi.UDTValue that receives CassandraRowMetadata as a constructor parameter.
I decided to align the approaches in those UDTValue classes. 
Unit tests were not executed. The jar …

SPARKC-647 UDTValue performance fix - reuse CassandraRowMetadata instead of building it for each row

---

project/Versions.scala

This should fix JAVA-2936 that we observe in our
performance tests.

SPARKC-656 update java driver to 4.12.0

---

.github/workflows/main.yml
connector/src/it/scala/com/datastax/spark/connector/cql/CassandraConnectorSpec.scala
doc/developers.md
project/Testing.scala

N/A as it worked correctly on older patch/RC versions of DSE & OSS C*
Describe the problem, or state of the project that this patch fixes. Explain
why this is a problem if this isn't obvious.
Testing the latest patch release versions for compatibility
N/A
Updated the GHA to test with latest versions
Fixes: [SPARKC-657](https://datastax-oss.atlassian.net/browse/SPARKC-657)
Almost all changes and especially bug fixes will require a test to be added to either the integration or Unit Tests. Any tests added will be automatically run on travis when the pull request is pushed to github. Be sure to run suites locally as well.
<details>
<summary>Click here to expand/collapse the local testing …

SPARKC-657 Bump DSE & OSS C* versions to current patch/RC releases

---

CHANGES.txt
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinExec.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala
project/Versions.scala

`master` branch is now dedicated to SCC 3.1.x with Spark 3.1 support
`b3.0` branch is now dedicated to SCC 3.0.x with Spark 3.0 support

SPARKC-646 Spark 3.1 support on master branch

---

.github/workflows/main.yml

GitHub no longer supports unauthenticated git protocol.

Switch ccm dependency URL from git to https protocol

---

connector/src/it/scala/com/datastax/spark/connector/types/TupleTypeSpec.scala
connector/src/it/scala/com/datastax/spark/connector/types/UserDefinedTypeSpec.scala
driver/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
driver/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala

For types containing `BLOB`s, the low-level Cassandra driver returned `fieldValue: HeapByteBuffer`. The `set` method that takes `Class<ValueT>` as the third parameter does not accept covariant classes (so it was unable to find the `BLOB <-> ByteBuffer` codec).
https://github.com/datastax/java-driver/pull/1555#issuecomment-855236502
Reverts to usage of the default registry implementation that is covariant with regard to type.
Fixes: [SPARKC-673](https://datastax-oss.atlassian.net/browse/SPARKC-673)
This is the previous working implementation from before f1f666cc650d638f0dcc7bf23737274476b63eaa.

SPARKC-673 Fix invalid call to CodecRegistry

---

README.md
connector/src/it/scala/com/datastax/bdp/spark/search/SearchAnalyticsIntegrationSpec.scala
connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/SaiBaseSpec.scala
connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogTableReadSpec.scala
connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
connector/src/it/scala/com/datastax/spark/connector/util/CatalystUtil.scala
connector/src/main/scala/com/datastax/spark/connector/cql/AuthConf.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraMetadataFunctions.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/SolrPredicateRules.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinExec.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala
doc/14_data_frames.md
project/Versions.scala

Continuing @alexott 's work from [1333](https://github.com/datastax/spark-cassandra-connector/pull/1333). There were tests failing and I believe the reason was the new adaptive query execution, which was [enabled by default](https://issues.apache.org/jira/browse/SPARK-33679) in 3.2.
I resolved a few tests by simply handling the case of `AdaptiveSparkPlanExec` (the `BatchScanExec` object was nested within it), and another test by including `spark_catalog` as a valid cassandra catalog name (not 100% sure this is the desired handling of this test, let me know what you think).

Compatibility with Spark 3.2

---

connector/src/it/scala/com/datastax/spark/connector/types/TupleTypeSpec.scala
connector/src/it/scala/com/datastax/spark/connector/types/UserDefinedTypeSpec.scala
driver/src/main/scala/com/datastax/spark/connector/types/TupleType.scala
driver/src/main/scala/com/datastax/spark/connector/types/UserDefinedType.scala

Fix regression introduced in f1f666cc650d638f0dcc7bf23737274476b63eaa
Describe the problem, or state of the project that this patch fixes. Explain
why this is a problem if this isn't obvious.
Example: 
"When I read from tables with 3 INTS I get a ThreeIntException(). This is a problem because I often want to read from a table with three integers."
Example: "I removed the incorrect assertion which would throw the ThreeIntException. This exception was incorrectly added and the assertion is not actually needed."
Fixes: [Put JIRA Reference HERE](https://datastax-oss.atlassian.net/projects/SPARKC)
Almost all changes and especially bug fixes will require a test to be added to either the …

SPARKC-673 Fix invalid call to CodecRegistry (#1334)

---

CHANGES.txt
connector/src/it/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinSpec.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/JoinHelper.scala

Cassandra Direct Join doesn't quote keyspace and table names causing issues in special cases, such as when the keyspace name starts with a number. See the [linked issue](https://datastax-oss.atlassian.net/browse/SPARKC-667).
Using the `asCql` method of `CqlIdentifier` to quote keyspace and table name in `JoinHelper`.
Fixes: [SPARKC-667](https://datastax-oss.atlassian.net/browse/SPARKC-667)
Add integration test in `CassandraDirectJoinSpec` to verify the resolution of the issue. The test fails without the fix.
It creates a new keyspace with the name starting with a digit, a simple key-value table, and tries to perform a direct join on that table.

SPARKC-667 Fix Cassandra Direct Join doesn't quote keyspace and table names (b3.0)

---

CHANGES.txt
connector/src/it/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinSpec.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/JoinHelper.scala

Cassandra Direct Join doesn't quote keyspace and table names causing issues in special cases, such as when the keyspace name starts with a number. See the [linked issue](https://datastax-oss.atlassian.net/browse/SPARKC-667).
Using the `asCql` method of `CqlIdentifier` to quote keyspace and table name in `JoinHelper`.
Fixes: [SPARKC-667](https://datastax-oss.atlassian.net/browse/SPARKC-667)
Add integration test in `CassandraDirectJoinSpec` to verify the resolution of the issue. The test fails without the fix.
It creates a new keyspace with the name starting with a digit, a simple key-value table, and tries to perform a direct join on that table.

SPARKC-667 Fix Cassandra Direct Join doesn't quote keyspace and table names (b3.1)

---

README.md
connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSpec.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/JoinHelper.scala

[SPARKC-682](https://datastax-oss.atlassian.net/browse/SPARKC-682) Support mixed case Cassandra column names when performing a DF join operation
When performing a DF join operation, Cassandra column names with mixed case is not handled properly leading to a column not found exception.
See description above. Without this patch, column names with mixed case will not be found during a DF join operation.
Per @jtgrabowski's suggestion, implement `.asCql(true)` to the join operation.
Fixes: [SPARKC-682](https://datastax-oss.atlassian.net/browse/SPARKC-682)
Almost all changes and especially bug fixes will require a test to be added to either the integration or Unit Tests. Any tests added …

SPARKC-682 Support mixed case Cassandra column names when performing DF join

---

connector/src/it/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinSpec.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala

`CassandraDirectJoinStrategy` doesn't consider the case that there are projections of direct join outputs. For example, `address` is a complex type field in cassandra table which is joined with other table:
```
left.join(right, left("id") === right("id"))
.select($"address.*")
.select($"street", $"city")
```
The extractors on `address` will be collapsed. So while building alias map in `CassandraDirectJoinStrategy`, it will fail by:
```
scala.MatchError: address#6337.street AS _extract_street#6354 (of class org.apache.spark.sql.catalyst.expressions.Alias)                                                                                                      
[info]   at org.apache.spark.sql.cassandra.execution.CassandraDirectJoinStrategy$.$anonfun$aliasMap$1(CassandraDirectJoinStrategy.scala:3 …
```

SPARKC-695: Fix projection collapse on CassandraDirectJoinStrategy

---

CHANGES.txt
README.md
connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/SaiBaseSpec.scala
connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
connector/src/it/scala/com/datastax/spark/connector/util/CatalystUtil.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/CassandraCatalog.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/CassandraScanBuilder.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala
project/Versions.scala

Spark Cassandra Connector did not work with Spark 3.3 before this patch
Updated Spark to 3.3, fixed compilation and tests
unit and integration tests

SPARKC-693 Support for Spark 3.3

---

connector/src/it/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinSpec.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala

We fixed projection collapse on `CassandraDirectJoinStrategy` in https://datastax-oss.atlassian.net/browse/SPARKC-695. But one incorrect assumption during collecting alias mappings is there is only one attribute under the extractor. If users build a struct before the join, and try to extract a field with an extractor, the assert will fail:
The incorrect assumption was fixed in this patch by collecting all attributes under aliased extractor.
Fixes: [SPARKC-700](https://datastax-oss.atlassian.net/browse/SPARKC-700)
Almost all changes and especially bug fixes will require a test to be added to either the integration or Unit Tests. Any tests added will be automatically run on travis when the pull request is pushed to github. Be sure to run suites locally as well.
[SPARKC-700]: …

SPARKC-700: Fix complex field extractor after join on CassandraDirectJoinStrategy

---

CHANGES.txt
README.md
connector/src/it/scala/com/datastax/spark/connector/SparkCassandraITFlatSpecBase.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/SaiBaseSpec.scala
connector/src/it/scala/com/datastax/spark/connector/datasource/CassandraCatalogTableSpec.scala
connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala
connector/src/it/scala/com/datastax/spark/connector/util/CatalystUtil.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/CassandraSourceRelation.scala
connector/src/main/scala/org/apache/spark/sql/cassandra/execution/CassandraDirectJoinStrategy.scala
doc/0_quick_start.md
doc/13_spark_shell.md
doc/15_python.md
project/Versions.scala

Support for Apache Spark 3.4 was missing.
Bumped Spark version and fixed compile/test issues.
Unit/Integration Tests

SPARKC-702: Added support for Spark 3.4

---

README.md
connector/src/main/java/com/datastax/spark/connector/japi/RDDAndDStreamCommonJavaFunctions.java
connector/src/main/scala/com/datastax/spark/connector/package.scala
rootdoc.txt

Addresses trademark violations against Apache projects.
Update community links to work, using the Apache Cassandra community page.

Improve language around project name

---

README.md
doc/16_partitioning.md

Removes two references to DS Academy courses and replaces them with links to the same courses on YouTube.
Two markdown files contained references to DataStax Academy courses that no longer exist at the referenced URLs.
I replaced the DS Academy course URLs with links to the same courses on YouTube 
Fixes: [SPARKC-707](https://datastax-oss.atlassian.net/browse/SPARKC-707)
Links in rendered markdown successfully open the correct video playlists in YouTube.
[SPARKC-707]: https://datastax-oss.atlassian.net/browse/SPARKC-707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SPARKC-707: Remove references to DataStax Academy

---

connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameSelectUdtSpec.scala
connector/src/main/scala/com/datastax/spark/connector/datasource/UnsafeRowReaderFactory.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/ClusterMode.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/mode/ExistingModeExecutor.scala

Spark Cassandra Connector was crashing with ClassCastExceptions when selecting UDT fields on pushed down Selections.
The cassandra calls always select whole fields. To my knowledge, cassandra has no possibility to select UDT fields directly. However the the decoder to spark expects only the selected UDT field to be presented. During decoding, it always decodes the first element (which may be of a different type) and thus failing with class cast exception, or in case of same types with a wrong value.
- UnsafeRowReader has now an extra decoder step which fulfils the decoding of projected UDT fields.
- The decoding is done by a new class `UdtProjectionDecoder`
- Added a new Cluster Mode "EXISTING" so that I can run integration tests on a locally running cassandra instance without relying on …

Fix for SPARKC-699: Projection of Sub Elements

---

.github/workflows/main.yml
README.md
build.sbt
connector/src/it/resources/log4j2.properties
connector/src/it/resources/logback.xml
connector/src/it/scala/com/datastax/spark/connector/cluster/Fixtures.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedKeySpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedListSpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedMapSpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedNumericSpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedSetSpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedStaticSpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/IndexedStringSpec.scala
connector/src/it/scala/com/datastax/spark/connector/cql/sai/SaiCollectionBaseSpec.scala
connector/src/it/scala/com/datastax/spark/connector/rdd/CassandraRDDSpec.scala
project/Dependencies.scala
project/Testing.scala
project/Versions.scala
project/build.properties
sbt/sbt
test-support/src/main/scala/com/datastax/spark/connector/ccm/CcmBridge.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/CcmConfig.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/mode/ClusterModeExecutor.scala
test-support/src/main/scala/com/datastax/spark/connector/ccm/mode/StandardModeExecutor.scala

Describe the problem, or state of the project that this patch fixes. Explain
why this is a problem if this isn't obvious.
Example: 
"When I read from tables with 3 INTS I get a ThreeIntException(). This is a problem because I often want to read from a table with three integers."
Example: "I removed the incorrect assertion which would throw the ThreeIntException. This exception was incorrectly added and the assertion is not actually needed."
Fixes: [Put JIRA Reference HERE](https://datastax-oss.atlassian.net/projects/SPARKC)
Almost all changes and especially bug fixes will require a test to be added to either the integration or Unit Tests. Any tests added will be automatically run on …

SPARKC-710: Update component versions

---

connector/src/main/scala/com/datastax/spark/connector/writer/AsyncExecutor.scala
connector/src/test/scala/com/datastax/spark/connector/writer/AsyncExecutorTest.scala

Handling of exceptions that may be thrown by `CqlSession#executeAsync()`. Otherwise semaphore in `AsyncExecutor` is not released and processing of further tasks blocked.
Fixes: [JAVA-3166](https://datastax-oss.atlassian.net/jira/software/c/projects/JAVA/issues/JAVA-3166)
[JAVA-3166]: https://datastax-oss.atlassian.net/browse/JAVA-3166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JAVA-3166: Enhanced exception handling of C* driver executeAsync()

---

README.md

Remove no longer existing community website/portal and replace it with Discord channel for collaboration.
n/a
Describe the problem, or state of the project that this patch fixes. Explain
why this is a problem if this isn't obvious.
There was no place for folks to ask questions as the community website was taken down a couple months ago.
Example: 
"When I read from tables with 3 INTS I get a ThreeIntException(). This is a problem because I often want to read from a table with three integers."
n/a
Example: "I removed the incorrect assertion which would throw the ThreeIntException. This exception was incorrectly added and the assertion is not actually needed."
Fixes: [Put JIRA Reference …

Document update to point to community support
